---

header_template: "## %new_version / %release_date"

entry_template: "* %title. Pull request [#%pull_request_number](%pull_request_url) by %pull_request_author"

extra_entry:
  template: "* %title."
  label: "rubygems: enhancement"

release_date_format: "%Y-%m-%d"

entry_wrapping: 74

changelog_label_mapping:
  "rubygems: feature": "### Features:"
  "rubygems: performance": "### Performance:"
  "rubygems: enhancement": "### Enhancements:"
  "rubygems: bug fix": "### Bug fixes:"
  "rubygems: security": "### Security:"
  "rubygems: breaking change": "### Breaking changes:"
  "rubygems: deprecation": "### Deprecations:"
  "rubygems: documentation": "### Documentation:"
  "rubygems: skip changelog": null

patch_level_labels:
  - "rubygems: performance"
  - "rubygems: enhancement"
  - "rubygems: bug fix"
  - "rubygems: security"
  - "rubygems: deprecation"
  - "rubygems: documentation"
  - "rubygems: skip changelog"
