---

header_template: "## %new_version (%release_date)"

entry_template: "  - %title [#%pull_request_number](%pull_request_url)"

release_date_format: "%Y-%m-%d"

changelog_label_mapping:
  "bundler: feature": "### Features:"
  "bundler: performance": "### Performance:"
  "bundler: enhancement": "### Enhancements:"
  "bundler: bug fix": "### Bug fixes:"
  "bundler: security": "### Security:"
  "bundler: breaking change": "### Breaking changes:"
  "bundler: deprecation": "### Deprecations:"
  "bundler: documentation": "### Documentation:"
  "bundler: skip changelog": null

patch_level_labels:
  - "bundler: performance"
  - "bundler: enhancement"
  - "bundler: bug fix"
  - "bundler: security"
  - "bundler: deprecation"
  - "bundler: documentation"
  - "bundler: skip changelog"
